version: '3.1'
services:
  squid:
    image: datadog/squid
    container_name: squid_proxy
    ports:
    - "3128:3128"
    volumes:
      - /data/squid/cache:/var/spool/squid
      - /data/squid/log:/var/log/squid
    