version: '3.3'

networks: 
  cpnv_srw3.docker: 
    external: 
      name: cpnv_srw3.docker

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NginxProxyManager
    hostname: nginxproxymanager

    restart: always
    ports:
      - '80:80'
      #- '82:81'
      - '443:443'
    volumes:
      - /data/rpm/data:/data
      - /data/rpm/letsencrypt:/etc/letsencrypt
    networks:
      - cpnv_srw3.docker