version: '3.3'

networks:
  srw3:
    driver: bridge

services:
# =================================================================================
# keycloak / Postgre
  postgres-cas:
    container_name: postgres-cas
    image: postgres
    hostname: postgres-cas
    volumes:
      - /data/postgre/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - srw3
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    hostname: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
       - postgres-cas
    networks:
      - srw3

# =================================================================================
# OpenLDAP / PHPLdapAdmin
  openldap:
    container_name: openldap
    build: ./ldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - /data/openldap/certificates:/container/service/slapd/assets/certs
      - /data/openldap/slapd/database:/var/lib/ldap
      - /data/openldap/slapd/config:/etc/ldap/slapd.d
    environment: 
      LDAP_ORGANISATION: cpnv-srw3
      LDAP_DOMAIN: cpnv-srw3.ch
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin_pass
      LDAP_CONFIG_PASSWORD: conf_pass
      LDAP_BASE_DN: "dc=cpnv-srw3,dc=ch"
      LDAP_TLS_CRT_FILENAME: server.crt
      LDAP_TLS_KEY_FILENAME: server.key
      LDAP_TLS_CA_CRT_FILENAME: cpnv-srw3.ch.ca.crt
    networks:
      - srw3

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "8081:80"
    environment: 
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - srw3

# =================================================================================
# Wordpress / mysql
  wordpress:
    image: wordpress
    restart: always
    hostname: wordpress
    container_name: wordpress
    ports:
      - 81:80
    networks:
      - srw3
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: wdbuser
      WORDPRESS_DB_PASSWORD: wdbpass
      WORDPRESS_DB_NAME: wdb
    volumes:
      - /data/wordpress/www:/var/www/html
    depends_on:
      - wordpressdb

  wordpressdb:
    image: mysql:latest
    restart: always
    hostname: wordpressdb
    container_name: wordpressdb
    networks:
      - srw3
    environment:
      MYSQL_DATABASE: wdb
      MYSQL_USER: wdbuser
      MYSQL_PASSWORD: wdbpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /data/mysql_wordpress:/var/lib/mysql