version: '3.1'

services:
  web1:
    build: ./web1
    container_name: web1
    ports:
    - "81:80"
  web2:
    build: ./web2
    container_name: web2
    ports:
    - "82:80"
  loadbalancer:
    build: ./loadbalancer
    container_name: loadbalancer
    ports:
    - "80:80"
    depends_on:
    - web1
    - web2