version: '3.3'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - /data/openldap/certificates:/container/service/slapd/assets/certs
      - /data/openldap/slapd/database:/var/lib/ldap
      - /data/openldap/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=cpnv-srw3.ch.ca.crt
    networks:
      - srw3
  
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "80:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - srw3

networks:
  srw3:
    driver: bridge