version: '3.3'

volumes:
  postgres_data:
    driver: local
networks:
  srw3:
    driver: bridge

services:
  postgres:
    container_name: postgres-cas
    image: postgres
    hostname: postgres-cas
    volumes:
      - /data/postgre/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - srw3
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    hostname: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
       - postgres
    networks:
      - srw3